//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drone_Management_Sys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int CustId { get; set; }
        [Required]
        [DisplayName("Customer Name")]
        public string CustName { get; set; }
        [DisplayName("Gender")]
        [Required]

        public string Sex { get; set; }
        [DisplayName("Username")]
        [Required]

        public string username { get; set; }
        [DisplayName("Password")]
        [Required]

        public string password { get; set; }
    }
}
