//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drone_Management_Sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroneProfile
    {
        public int DroneID { get; set; }
        public string DroneName { get; set; }
        public int DroneCost { get; set; }
        public string DroneModelNumber { get; set; }
    }
}
